import React, { createContext, useContext, useState, useEffect } from 'react';
import api from '../utils/api';
import { useAuth } from './AuthContext';

const PreferencesContext = createContext();

const dictionary = {
  en: {
    dashboard: 'Dashboard',
    browseQuizzes: 'Browse Quizzes',
    dailyChallenge: 'Daily Challenge',
    learningPaths: 'Learning Paths',
    myResults: 'My Results',
    analytics: 'Analytics',
    activityMap: 'Activity Map',
    aiCoach: 'AI Coach',
    bookmarks: 'Bookmarks',
    studyNotes: 'Study Notes',
    leaderboard: 'Leaderboard',
    certificates: 'Certificates',
    profile: 'Profile',
    preferences: 'Preferences',
    upgradePlan: 'Upgrade Plan',
    signOut: 'Sign Out',
    myQuizzes: 'My Quizzes',
    createQuiz: 'Create Quiz',
    gradeBook: 'Grade Book',
    recentSubmissions: 'Recent Submissions',
    overview: 'Overview',
    users: 'Users',
    groups: 'Groups',
    myGroups: 'My Groups',
    quizzes: 'Quizzes',
    announcements: 'Announcements',
    auditLogs: 'Audit Logs',
    settings: 'Settings',
    preferencesSubtitle: 'Customize your admin interface experience',
    appearance: 'Appearance',
    lightMode: 'Light Mode',
    colorBlindMode: 'Color Blind Mode',
    fontSize: 'Font Size',
    language: 'Language',
    interaction: 'Interaction',
    soundEffects: 'Sound Effects',
    keyboardShortcuts: 'Keyboard Shortcuts',
    emailNotifications: 'Email Notifications',
    savePreferences: 'Save Preferences',
    saving: 'Saving...',
    lightModeSub: 'Use light background',
    colorBlindModeSub: 'Alternative color palette',
    fontSizeSub: 'Adjust text size',
    languageSub: 'Interface language',
    soundEffectsSub: 'Audio feedback on system actions',
    keyboardShortcutsSub: 'Enable quick navigation hotkeys',
    emailNotificationsSub: 'Receive administrative alerts by email',
    platformOverview: 'Platform Overview',
    platformOverviewSub: 'Manage users, quizzes, groups, and institute settings from one place.',
    totalStudents: 'Total Students',
    totalFaculty: 'Total Faculty',
    totalQuizzes: 'Total Quizzes',
    totalAttempts: 'Total Attempts',
    published: 'Published',
    passRate: 'Pass Rate',
    weeklyAttempts: 'Weekly Attempts',
    recentAttempts: 'Recent Attempts',
    seeAll: 'See all',
    addNewUser: 'Add New User',
    sendAnnouncement: 'Send Announcement',
    instituteSettings: 'Institute Settings',
    manageUsers: 'Manage Users',
    manageUsersSub: 'All accounts registered in the system',
    manageGroups: 'Manage Groups',
    manageGroupsSub: 'Create groups and organize student divisions',
    manageQuizzes: 'Manage Quizzes',
    manageQuizzesSub: 'Create, schedule, edit and view quiz results',
    broadcastAnnouncements: 'Broadcast Announcements',
    broadcastAnnouncementsSub: 'Broadcast real-time push notifications and emails',
    securityAuditLogs: 'Security Audit Logs',
    securityAuditLogsSub: 'View system action logging',
    instituteSettingsSub: 'Manage global platform configuration',
    createGroup: 'Create Group'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    browseQuizzes: 'क्विज़ खोजें',
    dailyChallenge: 'दैनिक चुनौती',
    learningPaths: 'सीखने के मार्ग',
    myResults: 'मेरे परिणाम',
    analytics: 'विश्लेषण',
    activityMap: 'गतिविधि मानचित्र',
    aiCoach: 'एआई कोच',
    bookmarks: 'बुकमार्क',
    studyNotes: 'अध्ययन नोट्स',
    leaderboard: 'लीडरबोर्ड',
    certificates: 'प्रमाण पत्र',
    profile: 'प्रोफ़ाइल',
    preferences: 'पसंद',
    upgradePlan: 'योजना अपग्रेड करें',
    signOut: 'साइन आउट',
    myQuizzes: 'मेरी क्विज़',
    createQuiz: 'क्विज़ बनाएं',
    gradeBook: 'ग्रेड बुक',
    recentSubmissions: 'हाल के सबमिशन',
    overview: 'अवलोकन',
    users: 'उपयोगकर्ता',
    groups: 'समूह',
    myGroups: 'मेरे समूह',
    quizzes: 'क्विज़',
    announcements: 'घोषणाएँ',
    auditLogs: 'ऑडिट लॉग',
    settings: 'सेटिंग्स',
    preferencesSubtitle: 'अपने एडमिन इंटरफ़ेस अनुभव को अनुकूलित करें',
    appearance: 'सजावट',
    lightMode: 'लाइट मोड',
    colorBlindMode: 'कलर ब्लाइंड मोड',
    fontSize: 'फ़ॉन्ट आकार',
    language: 'भाषा',
    interaction: 'इंटरैक्शन',
    soundEffects: 'ध्वनि प्रभाव',
    keyboardShortcuts: 'कीबोर्ड शॉर्टकट्स',
    emailNotifications: 'ईमेल सूचनाएं',
    savePreferences: 'पसंद सहेजें',
    saving: 'सहेज रहा है...',
    lightModeSub: 'हल्की पृष्ठभूमि का उपयोग करें',
    colorBlindModeSub: 'वैकल्पिक रंग पैलेट',
    fontSizeSub: 'पाठ का आकार समायोजित करें',
    languageSub: 'इंटरफ़ेस भाषा',
    soundEffectsSub: 'सिस्टम क्रियाओं पर ऑडियो प्रतिक्रिया',
    keyboardShortcutsSub: 'त्वरित नेविगेशन हॉटकी सक्षम करें',
    emailNotificationsSub: 'ईमेल द्वारा प्रशासनिक अलर्ट प्राप्त करें',
    platformOverview: 'प्लेटफ़ॉर्म अवलोकन',
    platformOverviewSub: 'एक ही स्थान से उपयोगकर्ताओं, क्विज़, समूहों और संस्थान सेटिंग्स को प्रबंधित करें।',
    totalStudents: 'कुल छात्र',
    totalFaculty: 'कुल संकाय',
    totalQuizzes: 'कुल क्विज़',
    totalAttempts: 'कुल प्रयास',
    published: 'प्रकाशित',
    passRate: 'उत्तीर्ण दर',
    weeklyAttempts: 'साप्ताहिक प्रयास',
    recentAttempts: 'हाल के प्रयास',
    seeAll: 'सभी देखें',
    addNewUser: 'नया उपयोगकर्ता जोड़ें',
    sendAnnouncement: 'घोषणा भेजें',
    instituteSettings: 'संस्थान सेटिंग्स',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    manageUsersSub: 'सिस्टम में पंजीकृत सभी खाते',
    manageGroups: 'समूह प्रबंधित करें',
    manageGroupsSub: 'समूह बनाएं और छात्र प्रभागों को व्यवस्थित करें',
    manageQuizzes: 'क्विज़ प्रबंधित करें',
    manageQuizzesSub: 'क्विज़ बनाएं, शेड्यूल करें, संपादित करें और परिणाम देखें',
    broadcastAnnouncements: 'घोषणाएँ प्रसारित करें',
    broadcastAnnouncementsSub: 'वास्तविक समय में पुश सूचनाएं और ईमेल प्रसारित करें',
    securityAuditLogs: 'सुरक्षा ऑडिट लॉग',
    securityAuditLogsSub: 'सिस्टम क्रिया लॉगिंग देखें',
    instituteSettingsSub: 'वैश्विक प्लेटफ़ॉर्म कॉन्फ़िगरेशन प्रबंधित करें',
    createGroup: 'समूह बनाएँ'
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    browseQuizzes: 'क्विझ शोधा',
    dailyChallenge: 'दैनिक आव्हान',
    learningPaths: 'शिकण्याचे मार्ग',
    myResults: 'माझे निकाल',
    analytics: 'विश्लेषण',
    activityMap: 'कृती नकाशा',
    aiCoach: 'एआय कोच',
    bookmarks: 'बुकमार्क',
    studyNotes: 'अभ्यास नोट्स',
    leaderboard: 'लीडरबोर्ड',
    certificates: 'प्रमाणपत्रे',
    profile: 'प्रोफाइल',
    preferences: 'पसंती',
    upgradePlan: 'योजना अपग्रेड करा',
    signOut: 'साइन आउट',
    myQuizzes: 'माझ्या क्विझ',
    createQuiz: 'क्विझ तयार करा',
    gradeBook: 'गुण नोंदवही',
    recentSubmissions: 'अलीकडील सबमिशन',
    overview: 'आढावा',
    users: 'वापरकर्ते',
    groups: 'गट',
    myGroups: 'माझे गट',
    quizzes: 'क्विझ',
    announcements: 'घोषणा',
    auditLogs: 'ऑडिट लॉग',
    settings: 'सेटिंग्ज',
    preferencesSubtitle: 'तुमचा ॲडमिन इंटरफेस अनुभव सानुकूलित करा',
    appearance: 'देखावा',
    lightMode: 'लाइट मोड',
    colorBlindMode: 'कलर ब्लाइंड मोड',
    fontSize: 'फॉन्ट आकार',
    language: 'भाषा',
    interaction: 'परस्पर क्रिया',
    soundEffects: 'ध्वनी प्रभाव',
    keyboardShortcuts: 'कीबोर्ड शॉर्टकट',
    emailNotifications: 'ईमेल अधिसूचना',
    savePreferences: 'पसंती जतन करा',
    saving: 'जतन करत आहे...',
    lightModeSub: 'प्रकाश पार्श्वभूमी वापरा',
    colorBlindModeSub: 'पर्यायी रंग पॅलेट',
    fontSizeSub: 'मजकूराचा आकार समायोजित करा',
    languageSub: 'इंटरफेस भाषा',
    soundEffectsSub: 'सिस्टम कृतींवर ऑडिओ फीडबॅक',
    keyboardShortcutsSub: 'जलद नेव्हिगेशन हॉटकीज सक्षम करा',
    emailNotificationsSub: 'ईमेलद्वारे प्रशासकीय इशारे मिळवा',
    platformOverview: 'प्लॅटफॉर्म विहंगावलोकन',
    platformOverviewSub: 'वापरकर्ते, क्विझ, गट आणि संस्था सेटिंग्ज एकाच ठिकाणाहून व्यवस्थापित करा.',
    totalStudents: 'एकूण विद्यार्थी',
    totalFaculty: 'एकूण शिक्षक',
    totalQuizzes: 'एकूण क्विझ',
    totalAttempts: 'एकूण प्रयत्न',
    published: 'प्रकाशित',
    passRate: 'उत्तीर्ण दर',
    weeklyAttempts: 'साप्ताहिक प्रयत्न',
    recentAttempts: 'अलीकडील प्रयत्न',
    seeAll: 'सर्व पहा',
    addNewUser: 'नवीन वापरकर्ता जोडा',
    sendAnnouncement: 'घोषणा पाठवा',
    instituteSettings: 'संस्था सेटिंग्ज',
    manageUsers: 'वापरकर्ते व्यवस्थापित करा',
    manageUsersSub: 'सिस्टममध्ये नोंदणीकृत सर्व खाती',
    manageGroups: 'गट व्यवस्थापित करा',
    manageGroupsSub: 'गट तयार करा आणि विद्यार्थी विभाग आयोजित करा',
    manageQuizzes: 'क्विझ व्यवस्थापित करा',
    manageQuizzesSub: 'क्विझ तयार करा, शेड्यूल करा, संपादित करा आणि निकाल पहा',
    broadcastAnnouncements: 'घोषणा प्रसारित करा',
    broadcastAnnouncementsSub: 'रिअल-टाइम पुश सूचना आणि ईमेल प्रसारित करा',
    securityAuditLogs: 'सुरक्षा ऑडिट लॉग',
    securityAuditLogsSub: 'सिस्टम कृती लॉगिंग पहा',
    instituteSettingsSub: 'जागतिक प्लॅटफॉर्म कॉन्फिगरेशन व्यवस्थापित करा',
    createGroup: 'गट तयार करा'
  },
  ta: {
    dashboard: 'கட்டுப்பாட்டகம்',
    browseQuizzes: 'வினாடி வினாக்களை உலாவு',
    dailyChallenge: 'தினசரி சவால்',
    learningPaths: 'கற்றல் பாதைகள்',
    myResults: 'என் முடிவுகள்',
    analytics: 'பகுப்பாய்வு',
    activityMap: 'செயல்பாட்டு வரைபடம்',
    aiCoach: 'AI பயிற்சியாளர்',
    bookmarks: 'புத்தகக்குறிகள்',
    studyNotes: 'படிப்பு குறிப்புகள்',
    leaderboard: 'முன்னணி பலகை',
    certificates: 'சான்றிதழ்கள்',
    profile: 'சுயவிவரம்',
    preferences: 'விருப்பங்கள்',
    upgradePlan: 'திட்டத்தை மேம்படுத்து',
    signOut: 'வெளியேறு',
    myQuizzes: 'எனது வினாடி வினாக்கள்',
    createQuiz: 'உருவாக்கு',
    gradeBook: 'மதிப்பெண் புத்தகம்',
    recentSubmissions: 'சமீபத்திய சமர்ப்பிப்புகள்',
    overview: 'கண்ணோட்டம்',
    users: 'பயனர்கள்',
    groups: 'குழுக்கள்',
    myGroups: 'எனது குழுக்கள்',
    quizzes: 'வினாடி வினாக்கள்',
    announcements: 'அறிவிப்புகள்',
    auditLogs: 'தணிக்கை பதிவுகள்',
    settings: 'அமைப்புகள்',
    preferencesSubtitle: 'உங்கள் நிர்வாக இடைமுக அனுபவத்தைத் தனிப்பயனாக்குங்கள்',
    appearance: 'தோற்றம்',
    lightMode: 'ஒளி பயன்முறை',
    colorBlindMode: 'வண்ண குருட்டு முறை',
    fontSize: 'எழுத்துரு அளவு',
    language: 'மொழி',
    interaction: 'ஊடாடல்',
    soundEffects: 'ஒலி விளைவுகள்',
    keyboardShortcuts: 'விசைப்பலகை குறுக்குவழிகள்',
    emailNotifications: 'மின்னஞ்சல் அறிவிப்புகள்',
    savePreferences: 'விருப்பங்களைச் சேமி',
    saving: 'சேமிக்கிறது...',
    lightModeSub: 'ஒளி பின்னணியைப் பயன்படுத்தவும்',
    colorBlindModeSub: 'மாற்று வண்ண தட்டு',
    fontSizeSub: 'உரை அளவை சரிசெய்யவும்',
    languageSub: 'இடைமுக மொழி',
    soundEffectsSub: 'கணினி செயல்பாடுகளில் ஒலி கருத்து',
    keyboardShortcutsSub: 'விரைவு வழிசெலுத்தல் குறுக்குவழிகளை இயக்கு',
    emailNotificationsSub: 'மின்னஞ்சல் மூலம் நிர்வாக விழிப்பூட்டல்களைப் பெறுங்கள்',
    platformOverview: 'தளத்தின் கண்ணோட்டம்',
    platformOverviewSub: 'பயனர்கள், வினாடி வினாக்கள், குழுக்கள் மற்றும் நிறுவன அமைப்புகளை ஒரே இடத்திலிருந்து நிர்வகிக்கவும்.',
    totalStudents: 'மொத்த மாணவர்கள்',
    totalFaculty: 'மொத்த ஆசிரியர்கள்',
    totalQuizzes: 'மொத்த வினாடி வினாக்கள்',
    totalAttempts: 'மொத்த முயற்சிகள்',
    published: 'வெளியிடப்பட்டது',
    passRate: 'தேர்ச்சி விகிதம்',
    weeklyAttempts: 'வாராந்திர முயற்சிகள்',
    recentAttempts: 'சமீபத்திய முயற்சிகள்',
    seeAll: 'அனைத்தையும் காட்டு',
    addNewUser: 'புதிய பயனரைச் சேர்',
    sendAnnouncement: 'அறிவிப்பை அனுப்பு',
    instituteSettings: 'நிறுவன அமைப்புகள்',
    manageUsers: 'பயனர்களை நிர்வகி',
    manageUsersSub: 'கணினியில் பதிவுசெய்யப்பட்ட அனைத்து கணக்குகள்',
    manageGroups: 'குழுக்களை நிர்வகி',
    manageGroupsSub: 'குழுக்களை உருவாக்கி மாணவர் பிரிவுகளை ஒழுங்கமைக்கவும்',
    manageQuizzes: 'வினாடி வினாக்களை நிர்வகி',
    manageQuizzesSub: 'வினாடி வினாக்களை உருவாக்கவும், திட்டமிடவும், திருத்தவும் மற்றும் முடிவுகளைப் பார்க்கவும்',
    broadcastAnnouncements: 'அறிவிப்புகளைப் பரப்புங்கள்',
    broadcastAnnouncementsSub: 'நிகழ்நேர புஷ் அறிவிப்புகள் மற்றும் மின்னஞ்சல்களைப் பரப்புங்கள்',
    securityAuditLogs: 'பாதுகாப்பு தணிக்கை பதிவுகள்',
    securityAuditLogsSub: 'கணினி செயல் பதிவுகளைப் பார்க்கவும்',
    instituteSettingsSub: 'உலகளாவிய தள உள்ளமைவை நிர்வகிக்கவும்',
    createGroup: 'குழுவை உருவாக்கு'
  },
  te: {
    dashboard: 'డ్యాష్‌బోర్డ్',
    browseQuizzes: 'క్విజ్‌లను బ్రౌజ్ చేయండి',
    dailyChallenge: 'రోజువారీ సవాలు',
    learningPaths: 'అభ్యాస మార్గాలు',
    myResults: 'నా ఫలితాలు',
    analytics: 'విశ్లేషణలు',
    activityMap: 'కార్యకలాప పటం',
    aiCoach: 'AI కోచ్',
    bookmarks: 'బుక్‌మార్క్‌లు',
    studyNotes: 'అధ్యయన గమనికలు',
    leaderboard: 'లీడర్‌బోర్డ్',
    certificates: 'ధృవపత్రాలు',
    profile: 'ప్రొఫైల్',
    preferences: 'ప్రాధాన్యతలు',
    upgradePlan: 'ప్లాన్ అప్‌గ్రేడ్ చేయండి',
    signOut: 'లాగ్ అవుట్',
    myQuizzes: 'నా క్విజ్‌లు',
    createQuiz: 'క్విజ్ సృష్టించండి',
    gradeBook: 'గ్రేడ్ బుక్',
    recentSubmissions: 'ఇటీవలి సమర్పణలు',
    overview: 'అవలోకనం',
    users: 'వినియోగదారులు',
    groups: 'సమూహాలు',
    myGroups: 'నా సమూహాలు',
    quizzes: 'క్విజ్‌లు',
    announcements: 'ప్రకటనలు',
    auditLogs: 'ఆడిట్ లాగ్‌లు',
    settings: 'సెట్టింగులు',
    preferencesSubtitle: 'మీ అడ్మిన్ ఇంటర్‌ఫేస్ అనుభవాన్ని అనుకూలీకరించండి',
    appearance: 'రూపం',
    lightMode: 'లైట్ మోడ్',
    colorBlindMode: 'కలర్ బ్లైండ్ మోడ్',
    fontSize: 'ఫాంట్ పరిమాణం',
    language: 'భాష',
    interaction: 'ఇంటరాక్షన్',
    soundEffects: 'ధ్వని ప్రభావాలు',
    keyboardShortcuts: 'కీబోర్డ్ షార్ట్‌కట్‌లు',
    emailNotifications: 'ఇమెయిల్ నోటిఫికేషన్‌లు',
    savePreferences: 'ప్రాధాన్యతలను సేవ్ చేయి',
    saving: 'సేవ్ అవుతోంది...',
    lightModeSub: 'లైట్ బ్యాక్‌గ్రౌండ్ ఉపయోగించండి',
    colorBlindModeSub: 'ప్రత్యామ్నాయ రంగుల పాలెట్',
    fontSizeSub: 'టెక్స్ట్ పరిమాణాన్ని సర్దుబాటు చేయండి',
    languageSub: 'ఇంటర్‌ఫేస్ భాష',
    soundEffectsSub: 'సిస్టమ్ చర్యలపై ఆడియో ఫీడ్‌బ్యాక్',
    keyboardShortcutsSub: 'శీఘ్ర నావిగేషన్ హాట్‌కీలను ప్రారంభించండి',
    emailNotificationsSub: 'ఇమెయిల్ ద్వారా పరిపాలనా హెచ్చరికలను స్వీకరించండి',
    platformOverview: 'ప్లాట్‌ఫారమ్ అవలోకనం',
    platformOverviewSub: 'వినియోగదారులు, క్విజ్‌లు, సమూహాలు మరియు సంస్థ సెట్టింగ్‌లను ఒకే చోటు నుండి నిర్వహించండి.',
    totalStudents: 'మొత్తం విద్యార్థులు',
    totalFaculty: 'మొత్తం అధ్యాపకులు',
    totalQuizzes: 'మొత్తం క్విజ్‌లు',
    totalAttempts: 'మొత్తం ప్రయత్నాలు',
    published: 'ప్రచురించబడింది',
    passRate: 'ఉత్తీర్ణత రేటు',
    weeklyAttempts: 'వారపు ప్రయత్నాలు',
    recentAttempts: 'ఇటీవలి ప్రయత్నాలు',
    seeAll: 'అన్నీ చూడు',
    addNewUser: 'కొత్త వినియోగదారుని చేర్చు',
    sendAnnouncement: 'ప్రకటన పంపు',
    instituteSettings: 'సంస్థ సెట్టింగులు',
    manageUsers: 'వినియోగదారులను నిర్వహించు',
    manageUsersSub: 'సిస్టమ్‌లో నమోదైన అన్ని ఖాతాలు',
    manageGroups: 'సమూహాలను నిర్వహించు',
    manageGroupsSub: 'సమూహాలను సృష్టించండి మరియు విద్యార్థి విభాగాలను నిర్వహించండి',
    manageQuizzes: 'క్విజ్‌లను నిర్వహించు',
    manageQuizzesSub: 'క్విజ్‌లను సృష్టించండి, షెడ్యూల్ చేయండి, సవరించండి మరియు ఫలితాలను చూడండి',
    broadcastAnnouncements: 'ప్రకటనలను ప్రసారం చేయి',
    broadcastAnnouncementsSub: 'నిజ-సమయ పుష్ నోటిఫికేషన్‌లు మరియు ఇమెయిల్‌లను ప్రసారం చేయి',
    securityAuditLogs: 'భద్రతా ఆడిట్ లాగ్‌లు',
    securityAuditLogsSub: 'సిస్టమ్ చర్య లాగింగ్‌ను వీక్షించండి',
    instituteSettingsSub: 'గ్లోబల్ ప్లాట్‌ఫారమ్ కాన్ఫిగరేషన్‌ను నిర్వహించండి',
    createGroup: 'సమూహాన్ని సృష్టించు'
  },
};

export function PreferencesProvider({ children }) {
  const { user } = useAuth();
  const [prefs, setPrefs] = useState({
    colorBlindMode: false,
    fontSize: 'medium',
    language: 'en',
    soundEffects: true,
    keyboardShortcuts: true,
    emailNotifications: true
  });

  const loadPrefs = async () => {
    try {
      const r = await api.get('/preferences');
      if (r.data.success && r.data.data) {
        setPrefs(r.data.data);
      }
    } catch (err) {}
  };

  useEffect(() => {
    if (user) {
      loadPrefs();
    } else {
      setPrefs({
        colorBlindMode: false,
        fontSize: 'medium',
        language: 'en',
        soundEffects: true,
        keyboardShortcuts: true,
        emailNotifications: true
      });
    }
  }, [user]);

  // Apply visual settings to the body DOM element
  useEffect(() => {

    // 2. Color Blind Mode
    if (prefs.colorBlindMode) {
      document.body.classList.add('color-blind');
    } else {
      document.body.classList.remove('color-blind');
    }

    // 3. Font Size Accessibility
    document.body.classList.remove('font-small', 'font-medium', 'font-large');
    document.documentElement.classList.remove('font-small', 'font-medium', 'font-large');
    if (prefs.fontSize) {
      document.body.classList.add(`font-${prefs.fontSize}`);
      document.documentElement.classList.add(`font-${prefs.fontSize}`);
    } else {
      document.body.classList.add('font-medium');
      document.documentElement.classList.add('font-medium');
    }
  }, [prefs.colorBlindMode, prefs.fontSize]);

  const updatePrefs = async (newPrefs) => {
    try {
      const r = await api.put('/preferences', newPrefs);
      if (r.data.success) {
        setPrefs(r.data.data);
        return r.data.data;
      }
    } catch (err) {
      throw err;
    }
  };

  const t = (key) => {
    const lang = prefs.language || 'en';
    return dictionary[lang]?.[key] || dictionary['en']?.[key] || key;
  };

  return (
    <PreferencesContext.Provider value={{ prefs, setPrefs, updatePrefs, loadPrefs, t }}>
      {children}
    </PreferencesContext.Provider>
  );
}

export const usePreferences = () => useContext(PreferencesContext);
