import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Layout from '../../components/Layout';
import api from '../../utils/api';
import { BsAward, BsLightning, BsCompass, BsCheckCircle } from 'react-icons/bs';
import styles from './AICoach.module.css';

export default function AICoach() {
  const [coachData, setCoachData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/student/ai-coach')
      .then(r => setCoachData(r.data))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <Layout><div className={styles.center}><div className="spinner"/></div></Layout>;

  if (!coachData || !coachData.hasData) {
    return (
      <Layout>
        <div className={styles.emptyContainer}>
          <div className={styles.emptyIcon}>🤖</div>
          <h2>AI Study Coach is Offline</h2>
          <p>{coachData?.message || 'Please complete at least one quiz to generate personalized study insights!'}</p>
          <Link to="/student/quizzes" className={styles.btnPrimary}>Browse Quizzes</Link>
        </div>
      </Layout>
    );
  }

  const { tagStats, weakTags, recommendedQuizzes, studyPlan } = coachData;

  return (
    <Layout>
      <div className={styles.page}>
        <div className={styles.header}>
          <h1>🤖 AI Study Coach & Insights</h1>
          <p>Real-time weaknesses diagnostics and personalized study strategies generated by Gemini AI.</p>
        </div>

        <div className={styles.grid}>
          {/* Tag strengths */}
          <div className={styles.card}>
            <h3>🎯 Subject & Topic Strengths</h3>
            <div className={styles.statsList}>
              {tagStats.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '30px 10px', color: 'var(--gray-500)', fontSize: '0.9rem' }}>
                  📊 No quiz data analyzed yet. Attempt a quiz to see your topic strengths!
                </div>
              ) : (
                tagStats.map(s => {
                  const color = s.accuracy >= 75 ? '#10b981' : s.accuracy >= 55 ? '#f59e0b' : '#ef4444';
                  return (
                    <div key={s.tag} className={styles.statRow}>
                      <div className={styles.statLabel}>
                        <span className={styles.tagName}>{s.tag}</span>
                        <span className={styles.tagScore}>{s.correct}/{s.total} ({s.accuracy}%)</span>
                      </div>
                      <div className={styles.progressBg}>
                        <div className={styles.progressBar} style={{ width: `${s.accuracy}%`, background: color }} />
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>

          {/* Summary Diagnosis Box */}
          <div className={styles.card}>
            <h3>💡 AI Coach Diagnosis & Tips</h3>
            <div className={styles.planContent} style={{ whiteSpace: 'pre-wrap', fontSize: '0.9rem', lineHeight: '1.6' }}>
              {studyPlan}
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
